# Generated by Django 5.1.15 on 2026-09-16 12:42

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentIntent",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("provider", models.CharField(max_length=64)),
                ("provider_ref", models.CharField(blank=True, max_length=128)),
                ("amount", models.PositiveIntegerField()),
                ("currency", models.CharField(default="IRR", max_length=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requires_action", "Requires action"),
                            ("processing", "Processing"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="requires_action",
                        max_length=32,
                    ),
                ),
                ("idempotency_key", models.CharField(max_length=128, unique=True)),
                ("raw_response", models.JSONField(blank=True, default=dict)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
