# Generated by Django 5.1.15 on 2026-09-18 12:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0004_orderevent_alter_order_options_order_cancelled_at_and_more"),
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="paymentintent",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="paymentintent",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="paymentintent",
            name="correlation_id",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="paymentintent",
            name="failure_code",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="paymentintent",
            name="redirect_url",
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddIndex(
            model_name="paymentintent",
            index=models.Index(
                fields=["provider", "provider_ref"], name="payments_pa_provide_1001b2_idx"
            ),
        ),
    ]
