# Generated by Django 5.1.15 on 2026-09-16 12:42

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending_payment", "Pending payment"),
                            ("paid", "Paid"),
                            ("fulfilling", "Fulfilling"),
                            ("shipped", "Shipped"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=32,
                    ),
                ),
                ("currency", models.CharField(default="IRR", max_length=3)),
                ("total_amount", models.PositiveIntegerField(default=0)),
                (
                    "idempotency_key",
                    models.CharField(blank=True, max_length=128, null=True, unique=True),
                ),
                ("correlation_id", models.CharField(blank=True, max_length=64)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OrderLine",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("product_name", models.CharField(max_length=200)),
                ("sku", models.CharField(max_length=64)),
                ("quantity", models.PositiveIntegerField()),
                ("unit_price_amount", models.PositiveIntegerField()),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
