# Generated by Django 5.1.15 on 2026-09-16 13:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="staff_notes",
            field=models.TextField(blank=True, help_text="Internal staff notes"),
        ),
    ]
