# Generated by Django 5.1.15 on 2026-09-18 12:45

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0003_admin_phase1"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderEvent",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("status", models.CharField(max_length=32)),
                ("note", models.CharField(blank=True, max_length=255)),
                ("source", models.CharField(default="system", max_length=32)),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="order",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="order",
            name="cancelled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="contact_name",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="order",
            name="contact_phone",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="order",
            name="customer_note",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="order",
            name="discount_amount",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="order",
            name="paid_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_address",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_amount",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_method_code",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_method_title",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="order",
            name="stock_reserved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="order",
            name="subtotal_amount",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="orderline",
            name="color",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="orderline",
            name="image_url",
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="orderline",
            name="product_slug",
            field=models.SlugField(blank=True),
        ),
        migrations.AddField(
            model_name="orderline",
            name="size",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["user", "-created_at"], name="orders_orde_user_id_0ae59f_idx"
            ),
        ),
        migrations.AddField(
            model_name="orderevent",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="orders.order",
            ),
        ),
    ]
