# Generated by Django 5.1.15 on 2026-09-18 12:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shipping", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="shippingmethod",
            options={"ordering": ["sort_order", "price_amount"]},
        ),
        migrations.AddField(
            model_name="shippingmethod",
            name="description",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="shippingmethod",
            name="eta_days",
            field=models.PositiveIntegerField(
                default=0, help_text="Indicative delivery time in days"
            ),
        ),
        migrations.AddField(
            model_name="shippingmethod",
            name="free_over_amount",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Subtotal at which this method becomes free (minor units)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="shippingmethod",
            name="sort_order",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
