services:
  api:
    build:
      context: ../../apps/api
      dockerfile: ../docker/api.Dockerfile.dev
    volumes:
      - ../../apps/api:/app
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]

  worker:
    build:
      context: ../../apps/api
      dockerfile: ../docker/api.Dockerfile.dev
    volumes:
      - ../../apps/api:/app
    command: ["celery", "-A", "config.celery", "worker", "-l", "info"]

  web:
    build:
      context: ../../apps/web
      dockerfile: ../docker/web.Dockerfile.dev
    volumes:
      - ../../apps/web:/app
      - /app/node_modules
      - /app/.next
    environment:
      WATCHPACK_POLLING: "true"
    command: ["npm", "run", "dev"]
