# Generated by Django 5.1.15 on 2026-09-18 12:45

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="audience",
            field=models.CharField(
                choices=[("women", "Women"), ("men", "Men"), ("unisex", "Unisex")],
                default="unisex",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="care",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="product",
            name="material",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("url", models.URLField(max_length=500)),
                ("alt_text", models.CharField(blank=True, max_length=255)),
                ("color", models.CharField(blank=True, max_length=64)),
                ("position", models.PositiveIntegerField(default=0)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "ordering": ["position", "created_at"],
            },
        ),
    ]
